#include<stdio.h>
#include<conio.h>
void main()
{
int a,b,c,d,e,f;clrscr();
printf("before swapping \n");
printf("enter the value of a=\n");
scanf("%d",&a);
printf("enter the value of b=\n");
scanf("%d",&b);
printf("enter the value of c=\n");
scanf("%d",&c);
printf("enter the value of d=\n");
scanf("%d",&d);
printf("enter the value of e=\n");
scanf("%d",&e);
printf("enter the value of f=\n");
scanf("%d",&f);

a=a+b+c+d+e+f;
f=a-b-c-d-e-f;
a=a-b-c-d-e-f;
e=e+a+b+c+d+f;
b=e-a-b-c-d-f;
e=e-a-b-c-d-f;
d=d+a+b+c+e+f;
c=d-a-b-c-e-f;
d=d-a-b-c-e-f;
printf("after swapping \n");
printf("the value of a= %d\n",a);
printf("the value of b= %d\n",b);
printf("the value of c= %d\n",c);
printf("the value of d= %d\n",d);
printf("the value of e= %d\n",e);
printf("the value of f= %d",f);
getch();
}