#include<stdio.h>
#include<conio.h>
void main()
{
int i,j;
clrscr();
for(i=1;i<=3;i++)
{
 for(j=1;j<=3;j++)
 {
  if(i==1||i==5||(j==1)||j==5)
	{printf(" * ");}
	else
	{printf("   ");}
     }
   printf("\n");
  }

int n,f;
printf("
scanf("%d",f);
for(int i=;i<=n;i++)
{ for(int j=1;j<=n-i;j++){
   printf(" ");
 }
for(int k=1;k<=(2*i-1);k++)
{
if(k==1||k==(2*i-1))
{printf("*");}
else

printf(" ");


} printf ( " \n");
} getch();