/**
 * @Author: Dastan Alam
 * @Date:   01-12-2021  Wed 05:46:52 PM  17:12:00
 * @Last Modified by:   Dastan Alam
 * @Last Modified time: 12-04-2022  Tue 06:19:37 PM  18:04:00
 */
#include<stdio.h>
#include<conio.h>

//Calculator
int main()
{
 //clrscr();
 int a,b;
 printf("Enter two no.s=");
 scanf("%d%d",&a,&b);
 printf("Sum is=%d\n",a+b);
 printf("Diffrenceis=%d\n",a-b);
 printf("Product is=%d\n",a*b);
 printf("Division is=%d\n",a/b);
 printf("Press any key");
 //getch();
}

