package record;

                     //   this is an instance variable and not final .
public record ProductRecord(Integer productId, String productName) 
{

	static int a=0;          //=> static variable  
	static {}                //=> Static block
	static void print() {}   //=> Static method
	void printing() {}       //=> non-static method (instance method)
	
	
//	not allowed
//	int b=0;   => error user-define instance variable
//	productId=992; => error user-define instance variable
//	{}  => instance block cant defined
	
	
//	auto generated by compiler
//	toString()
//	equals(Object obj)
//	hashCode() method.
	
	// canonical contractor added by compiler auto
	public ProductRecord
	{

	}
	
	//Compact Constructor
	public ProductRecord
	{
		if(productId<=0)
		{
			System.err.println("Id is Invalid");
		}		
	}
}
